name: 🚀 Deploy to Combell via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 📤 Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v3

      - name: 📤 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.trackthetombe.webhosting.be
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          server-dir: /www/
